# Generated by Django 3.2 on 2021-04-17 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='grade',
            new_name='score',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.speciality')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='selection.grade'),
            preserve_default=False,
        ),
    ]
