# Generated by Django 3.2 on 2021-04-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_auto_20210417_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
