# Generated by Django 3.2 on 2021-04-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_auto_20210417_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
